import HeroSection from "@/components/HeroSection";
import { Helmet } from "react-helmet-async";
import ArchitectureSection from "@/components/ArchitectureSection";
import UseCasesScrollSection from "@/components/UseCasesScrollSection";
import DemoSection from "@/components/DemoSection";

import MoatSection from "@/components/MoatSection";
import ContactSection from "@/components/ContactSection";
import FAQ from "@/components/FAQ";

const homeFaqs = [
  {
    q: "What is Alexandria?",
    a: "Alexandria is an AI-native diligence engine for biopharma licensing and M&A deals. It cross-references a continuously refreshed pharma corpus and your own data room, runs the analysis (rNPV, Monte Carlo, key indicators), and returns decision-ready deliverables in your existing format.",
  },
  {
    q: "Who uses Alexandria?",
    a: "Investment banking healthcare teams, life-sciences consulting practices, and internal biopharma BD&L teams use Alexandria to compress licensing and M&A diligence from weeks to hours.",
  },
  {
    q: "How is Alexandria different from using a generic LLM?",
    a: "Generic LLMs do not have access to a curated, source-traced biopharma corpus, do not connect to your data room, and do not run the analysis layer (rNPV, Monte Carlo, comparable deals). Alexandria is built end-to-end for biopharma diligence — retrieval, reasoning, valuation, and deliverable output in one workspace.",
  },
  {
    q: "Is my data room secure?",
    a: "Yes. Your data room is processed locally and securely within your environment. Alexandria cross-references it against the live corpus without exposing confidential documents externally.",
  },
  {
    q: "What outputs does Alexandria produce?",
    a: "Alexandria produces decision-ready deliverables — diligence memos, rNPV models, Monte Carlo simulations, valuation comparables, and indicator summaries — formatted to match the deliverable templates your team already uses.",
  },
  {
    q: "How fast is it?",
    a: "A diligence pack that typically takes a deal team weeks to produce manually is generated by Alexandria in roughly ten minutes, with full source traceability on every data point.",
  },
];

const softwareSchema = {
  "@context": "https://schema.org",
  "@type": "SoftwareApplication",
  name: "Alexandria",
  applicationCategory: "BusinessApplication",
  applicationSubCategory: "Biopharma M&A and licensing diligence",
  operatingSystem: "Web",
  description:
    "AI-native diligence engine for biopharma licensing and M&A deals. Cross-references a live pharma corpus and your data room, runs rNPV and Monte Carlo analysis, and returns decision-ready deliverables.",
  url: "https://www.alexandrialabs.uk/",
  provider: { "@type": "Organization", name: "Alexandria", url: "https://www.alexandrialabs.uk/" },
  audience: {
    "@type": "BusinessAudience",
    audienceType: "Investment banking healthcare, life-sciences consulting, biopharma BD&L teams",
  },
};

const breadcrumbSchema = {
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  itemListElement: [
    { "@type": "ListItem", position: 1, name: "Home", item: "https://www.alexandrialabs.uk/" },
  ],
};

const Index = () => {
  return (
    <>
    <Helmet>
      <title>Alexandria — AI diligence for biopharma licensing &amp; M&amp;A</title>
      <meta name="description" content="Alexandria turns weeks of biopharma licensing and M&A diligence into ten-minute, decision-ready deliverables — rNPV, Monte Carlo, and a dynamic workspace over a live pharma corpus." />
      <link rel="canonical" href="https://www.alexandrialabs.uk/" />
      <meta property="og:title" content="Alexandria — AI diligence for biopharma licensing &amp; M&amp;A" />
      <meta property="og:description" content="Turn weeks of biopharma licensing and M&A diligence into ten-minute deliverables. rNPV, Monte Carlo, and a dynamic workspace over a live pharma corpus." />
      <meta property="og:url" content="https://www.alexandrialabs.uk/" />
      <meta property="og:type" content="website" />
      <script type="application/ld+json">{JSON.stringify(softwareSchema)}</script>
      <script type="application/ld+json">{JSON.stringify(breadcrumbSchema)}</script>
    </Helmet>
    <main className="min-h-screen">
      <HeroSection />
      <ArchitectureSection />
      <UseCasesScrollSection />
      <DemoSection />
      
      <MoatSection />
      <FAQ items={homeFaqs} />
      <ContactSection />
    </main>
    </>
  );
};

export default Index;
